# vim: ft=yaml
---
driver:
  name: linode

provisioner:
  name: salt_solo
  formula: mysql
  state_top:
    base:
      "*":
        - mysql

platforms:
  - name: debian_jessie

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        mysql.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - mysql
